qlib_init:
    provider_uri: &provider_uri '/home/qdata/qlib_data/futures_data'
    region: cn
market: &market clean_data
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    init_data: True
    start_time: 2005-01-01
    end_time: 2025-12-31
    fit_start_time: 2005-01-01
    fit_end_time: 2025-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              # col_list: &col_list ['STD5', 'TURNOVER_CLOSE', 'TMA5','TSUMP5', 'CORR5','RESI10','ROC60','CORR20',''KLOW']  
              col_list: &col_list ['MACD','ATR5','RSI5','RSI20','OBV5','label_ori','price_norm','VOLUME_CLOSE','WVMA5','BETA5','RSQR5','RVI',
              'RESI5','CLOSE','REFCLOSE','HOLD','OPEN','HIGH', 'LOW','RSI10','KDJ_K','KDJ_D','KDJ_J','CCI5','AOS','HIGH_QTLU5','REV5',
              "KMID","KLEN","KMID2","KUP","KUP2","KLOW","KLOW2","KSFT","KSFT2", 'STD5','MA5','QTLU5','CORD5','CNTD5','VSTD5','IMAX5','IMIN5','QTLUMA5',
              'KURT5','SKEW5','CNTP5','CNTN5','SUMP5','CORR5','RANK5','RANKMA5','DIFF','DEA','SUMPMA5','RSV5','BULLS',
              'IMXD5']                                      
    learn_processors:
        - class: DropnaLabel
    # label: ['Ref($close, -1)'] 
    label: ['$close'] 
    # label: ['$volume/100']

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2017-01-01
        end_time: 2020-08-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: FuturesProcessModel
        module_path: darts_pro.futures_process
        kwargs:
            GPU: [0] 
            batch_size: 12
            seed: 0
            n_jobs: 20
            log_every_n_steps: 50
            type: 'fit_futures_togather'
            n_epochs : 150
            save_dataset_file: False
            load_dataset_file: &load_dataset_file False
            batch_file_path: 'custom/data/asis/Futures_Begin_202212'
            pred_data_path: "/home/qdata/workflow/wf_backtest_flow_2023/task/118/dump_data/"   
            scheduler_config: 
               start_factor: 1
               end_factor: 0.05
               total_iters: 5e4
               # base_lr: 0.5e-4
               # max_lr: 1.5e-3
               # cycle_momentum: False
               # step_size_up: 100000
               # T_max: 5
               # eta_min: 0.001
            optimizer_kwargs:
               lr: 1e-3
               weight_decay: 1e-4
            optargs:
               provider_uri: *provider_uri
               market: *market
               data_type: 'combine'
               data_path: 'custom/data/aug/darts/all_nor.npy'
               work_dir: 'custom/data/darts'
               model_name: "Futures_cleanDataCross_rsvMainRange27RsvDetail_202502"
               model_type: 'mlp'
               load_weight: True 
               best_weight: False
               step_mode: 1
               pretrain_model_name: 'MLP_PRETRAIN_1000_202110'
               wave_period : &wave_period 30
               hidden_size: 32
               forecast_horizon: &forecast_horizon 2
               cut_len: 27
               dropout: 0.5
               past_split: [[0,15],[15,30]]
               target_mode: [6,3,2,1,3]
               scale_mode: [5,2,0,2,0]
               filter_conv_index: -1
    dataset:
        class: TFTFuturesDataset
        module_path: darts_pro.tft_futures_dataset
        kwargs:
            handler:
                class: FuturesDataHandler
                module_path: tft.tft_handler
                kwargs: *data_handler_config
            segments:
                train: [2006-01-01, 2025-02-28]
                valid: [2025-02-01, 2025-04-30]
                test: [2021-01-01, 2021-03-01]
            whole_data: False
            data_path: 'custom/data/aug/darts/all_nor.npy'
            load_dataset_file: *load_dataset_file
            aug_type: 'no'
            data_type: 'date_range'
            transform_inner: True
            scale_time_col: False
            instrument_pick: [600520,600521,600522]
            scaler_type: 'norm'
            model_type: 'tft'
            step_len: *wave_period
            pred_len: *forecast_horizon
            over_time: 2          
            low_threhold: -51
            high_threhold: 5   
            col_def:
                col_list: *col_list
                group_column: 'instrument'
                datetime_index_column: 'datetime_number'
                group_rank_column: 'instrument_rank'
                ext_column: ['near_basis_rate','dom_basis_rate']
                target_column: ['RSV5','RSV5','CCI5','SUMPMA5','RSV5']
                time_column: 'time_idx'    
                future_covariate_col: ['dayofweek','month','dayofmonth']   
                past_covariate_col: ['HOLD','KSFT','near_basis_rate','OBV5','WVMA5','BETA5','OPEN','HIGH', 'LOW','KMID','REFCLOSE','SKEW5','KDJ_K','dom_basis_rate','CORR5'
                                  ,'HOLD','KSFT','near_basis_rate','OBV5','WVMA5','BETA5','OPEN','HIGH', 'LOW','KMID','REFCLOSE','SKEW5','KDJ_K','dom_basis_rate','CORR5'
                                  ,'HOLD','KSFT','near_basis_rate','OBV5','WVMA5','BETA5','OPEN','HIGH', 'LOW','KMID','REFCLOSE','SKEW5','KDJ_K','dom_basis_rate','CORR5'
                                  ,'HOLD','KSFT','near_basis_rate','OBV5','WVMA5','BETA5','OPEN','HIGH', 'LOW','KMID','REFCLOSE','SKEW5','KDJ_K','dom_basis_rate','CORR5'
                                  ,'HOLD','KSFT','near_basis_rate','OBV5','WVMA5','BETA5','OPEN','HIGH', 'LOW','KMID','REFCLOSE','SKEW5','KDJ_K','dom_basis_rate','CORR5'
                                  ] 
                static_covariate_col: ['industry']    
